version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4

    working_directory: ~/react-intl-bundler
    steps:
      - checkout:
          path: ~/react-intl-bundler

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test
      - run: npm run build
